apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: prod-cicd-demo
  namespace: prod-demo

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-cicd-demo

  minReplicas: 2
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70