resources:
  - namespace.yaml
  - configmap.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - deployment-canary.yaml
  - service-canary.yaml
  - ingress-canary.yaml

  # - hpa.yaml