apiVersion: v1
kind: Service
metadata:
  name: prod-cicd-demo
  namespace: prod-demo
spec:
  type: LoadBalancer
  selector:
    app: prod-cicd-demo
  ports:
    - name: http
      port: 80
      targetPort: http
